# execute linter on {push, pull request}, only whenever python file changes are detected
name: pylint.yml

on:
  pull_request:
    paths: '**.py'

jobs:    
  execute:
    runs-on: ubuntu-latest
    container: kubricdockerhub/kubruntudev:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Lint with pylint
        run: |
          pylint --version
          pylint --rcfile=.pylintrc ./kubric
